2022-03-12 23:58:21,065 INFO    MainThread:28114 [wandb_setup.py:_flush():71] setting env: {}
2022-03-12 23:58:21,065 INFO    MainThread:28114 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-12 23:58:21,065 INFO    MainThread:28114 [wandb_init.py:_log_setup():371] Logging user logs to /home/aiotlab/projects/cuongdm/MEC1/wandb/run-20220312_235821-6gm79rfm/logs/debug.log
2022-03-12 23:58:21,065 INFO    MainThread:28114 [wandb_init.py:_log_setup():372] Logging internal logs to /home/aiotlab/projects/cuongdm/MEC1/wandb/run-20220312_235821-6gm79rfm/logs/debug-internal.log
2022-03-12 23:58:21,065 INFO    MainThread:28114 [wandb_init.py:init():404] calling init triggers
2022-03-12 23:58:21,065 INFO    MainThread:28114 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-03-12 23:58:21,065 INFO    MainThread:28114 [wandb_init.py:init():460] starting backend
2022-03-12 23:58:21,065 INFO    MainThread:28114 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-12 23:58:21,069 INFO    MainThread:28114 [backend.py:ensure_launched():216] starting backend process...
2022-03-12 23:58:21,075 INFO    MainThread:28114 [backend.py:ensure_launched():221] started backend process with pid: 28767
2022-03-12 23:58:21,076 INFO    MainThread:28114 [wandb_init.py:init():469] backend started and connected
2022-03-12 23:58:21,080 INFO    MainThread:28114 [wandb_init.py:init():533] updated telemetry
2022-03-12 23:58:21,101 INFO    MainThread:28114 [wandb_init.py:init():563] communicating current version
2022-03-12 23:58:22,722 INFO    MainThread:28114 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-12 23:58:22,722 INFO    MainThread:28114 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-12 23:58:23,043 INFO    MainThread:28114 [wandb_init.py:init():606] starting run threads in backend
2022-03-12 23:58:28,052 INFO    MainThread:28114 [wandb_run.py:_console_start():1810] atexit reg
2022-03-12 23:58:28,053 INFO    MainThread:28114 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-12 23:58:28,054 INFO    MainThread:28114 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-12 23:58:28,056 INFO    MainThread:28114 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-12 23:58:28,057 INFO    MainThread:28114 [wandb_init.py:init():633] run started, returning control to user process
2022-03-12 23:58:47,833 INFO    MainThread:28114 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-12 23:58:47,835 INFO    MainThread:28114 [wandb_run.py:_restore():1752] restore
2022-03-12 23:58:50,589 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 779
}

2022-03-12 23:58:50,799 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 779
}

2022-03-12 23:58:51,111 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 779
}

2022-03-12 23:58:52,085 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 15027
}

2022-03-12 23:58:52,188 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 15027
}

2022-03-12 23:58:52,290 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 15027
}

2022-03-12 23:58:52,401 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 779
  total_bytes: 15027
}

2022-03-12 23:58:52,503 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15027
  total_bytes: 15027
}

2022-03-12 23:58:52,605 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15027
  total_bytes: 15027
}

2022-03-12 23:58:52,708 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15027
  total_bytes: 15027
}

2022-03-12 23:58:52,810 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15027
  total_bytes: 15027
}

2022-03-12 23:58:52,912 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15027
  total_bytes: 15027
}

2022-03-12 23:58:53,013 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15027
  total_bytes: 15027
}

2022-03-12 23:58:53,273 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15027
  total_bytes: 15027
}

2022-03-12 23:58:53,928 INFO    MainThread:28114 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15027
  total_bytes: 15027
}
local_info {
}

2022-03-12 23:58:55,207 INFO    MainThread:28114 [wandb_run.py:_append_files():2180] logging synced files
